# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import kowitodb_pb2 as kowitodb__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in kowitodb_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class KowitoDBStub:
    """---- Service ----

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Insert = channel.unary_unary(
                '/kowitodb.KowitoDB/Insert',
                request_serializer=kowitodb__pb2.InsertRequest.SerializeToString,
                response_deserializer=kowitodb__pb2.InsertResponse.FromString,
                _registered_method=True)
        self.BatchInsert = channel.unary_unary(
                '/kowitodb.KowitoDB/BatchInsert',
                request_serializer=kowitodb__pb2.BatchInsertRequest.SerializeToString,
                response_deserializer=kowitodb__pb2.BatchInsertResponse.FromString,
                _registered_method=True)
        self.Get = channel.unary_unary(
                '/kowitodb.KowitoDB/Get',
                request_serializer=kowitodb__pb2.GetRequest.SerializeToString,
                response_deserializer=kowitodb__pb2.GetResponse.FromString,
                _registered_method=True)
        self.Update = channel.unary_unary(
                '/kowitodb.KowitoDB/Update',
                request_serializer=kowitodb__pb2.UpdateRequest.SerializeToString,
                response_deserializer=kowitodb__pb2.UpdateResponse.FromString,
                _registered_method=True)
        self.Delete = channel.unary_unary(
                '/kowitodb.KowitoDB/Delete',
                request_serializer=kowitodb__pb2.DeleteRequest.SerializeToString,
                response_deserializer=kowitodb__pb2.DeleteResponse.FromString,
                _registered_method=True)
        self.List = channel.unary_unary(
                '/kowitodb.KowitoDB/List',
                request_serializer=kowitodb__pb2.ListRequest.SerializeToString,
                response_deserializer=kowitodb__pb2.ListResponse.FromString,
                _registered_method=True)
        self.Search = channel.unary_unary(
                '/kowitodb.KowitoDB/Search',
                request_serializer=kowitodb__pb2.SearchRequest.SerializeToString,
                response_deserializer=kowitodb__pb2.SearchResponse.FromString,
                _registered_method=True)
        self.Ask = channel.unary_unary(
                '/kowitodb.KowitoDB/Ask',
                request_serializer=kowitodb__pb2.AskRequest.SerializeToString,
                response_deserializer=kowitodb__pb2.AskResponse.FromString,
                _registered_method=True)
        self.Remember = channel.unary_unary(
                '/kowitodb.KowitoDB/Remember',
                request_serializer=kowitodb__pb2.RememberRequest.SerializeToString,
                response_deserializer=kowitodb__pb2.RememberResponse.FromString,
                _registered_method=True)
        self.Sql = channel.unary_unary(
                '/kowitodb.KowitoDB/Sql',
                request_serializer=kowitodb__pb2.SqlRequest.SerializeToString,
                response_deserializer=kowitodb__pb2.SqlResponse.FromString,
                _registered_method=True)
        self.RecordTurn = channel.unary_unary(
                '/kowitodb.KowitoDB/RecordTurn',
                request_serializer=kowitodb__pb2.RecordTurnRequest.SerializeToString,
                response_deserializer=kowitodb__pb2.RecordTurnResponse.FromString,
                _registered_method=True)
        self.GetSession = channel.unary_unary(
                '/kowitodb.KowitoDB/GetSession',
                request_serializer=kowitodb__pb2.GetSessionRequest.SerializeToString,
                response_deserializer=kowitodb__pb2.GetSessionResponse.FromString,
                _registered_method=True)
        self.Stats = channel.unary_unary(
                '/kowitodb.KowitoDB/Stats',
                request_serializer=kowitodb__pb2.StatsRequest.SerializeToString,
                response_deserializer=kowitodb__pb2.StatsResponse.FromString,
                _registered_method=True)


class KowitoDBServicer:
    """---- Service ----

    """

    def Insert(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchInsert(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Get(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Update(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Delete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def List(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Search(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Ask(self, request, context):
        """High-level AI API
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Remember(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Sql(self, request, context):
        """SQL over the DataFusion engine
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecordTurn(self, request, context):
        """Agent conversation memory
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Stats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_KowitoDBServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Insert': grpc.unary_unary_rpc_method_handler(
                    servicer.Insert,
                    request_deserializer=kowitodb__pb2.InsertRequest.FromString,
                    response_serializer=kowitodb__pb2.InsertResponse.SerializeToString,
            ),
            'BatchInsert': grpc.unary_unary_rpc_method_handler(
                    servicer.BatchInsert,
                    request_deserializer=kowitodb__pb2.BatchInsertRequest.FromString,
                    response_serializer=kowitodb__pb2.BatchInsertResponse.SerializeToString,
            ),
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=kowitodb__pb2.GetRequest.FromString,
                    response_serializer=kowitodb__pb2.GetResponse.SerializeToString,
            ),
            'Update': grpc.unary_unary_rpc_method_handler(
                    servicer.Update,
                    request_deserializer=kowitodb__pb2.UpdateRequest.FromString,
                    response_serializer=kowitodb__pb2.UpdateResponse.SerializeToString,
            ),
            'Delete': grpc.unary_unary_rpc_method_handler(
                    servicer.Delete,
                    request_deserializer=kowitodb__pb2.DeleteRequest.FromString,
                    response_serializer=kowitodb__pb2.DeleteResponse.SerializeToString,
            ),
            'List': grpc.unary_unary_rpc_method_handler(
                    servicer.List,
                    request_deserializer=kowitodb__pb2.ListRequest.FromString,
                    response_serializer=kowitodb__pb2.ListResponse.SerializeToString,
            ),
            'Search': grpc.unary_unary_rpc_method_handler(
                    servicer.Search,
                    request_deserializer=kowitodb__pb2.SearchRequest.FromString,
                    response_serializer=kowitodb__pb2.SearchResponse.SerializeToString,
            ),
            'Ask': grpc.unary_unary_rpc_method_handler(
                    servicer.Ask,
                    request_deserializer=kowitodb__pb2.AskRequest.FromString,
                    response_serializer=kowitodb__pb2.AskResponse.SerializeToString,
            ),
            'Remember': grpc.unary_unary_rpc_method_handler(
                    servicer.Remember,
                    request_deserializer=kowitodb__pb2.RememberRequest.FromString,
                    response_serializer=kowitodb__pb2.RememberResponse.SerializeToString,
            ),
            'Sql': grpc.unary_unary_rpc_method_handler(
                    servicer.Sql,
                    request_deserializer=kowitodb__pb2.SqlRequest.FromString,
                    response_serializer=kowitodb__pb2.SqlResponse.SerializeToString,
            ),
            'RecordTurn': grpc.unary_unary_rpc_method_handler(
                    servicer.RecordTurn,
                    request_deserializer=kowitodb__pb2.RecordTurnRequest.FromString,
                    response_serializer=kowitodb__pb2.RecordTurnResponse.SerializeToString,
            ),
            'GetSession': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSession,
                    request_deserializer=kowitodb__pb2.GetSessionRequest.FromString,
                    response_serializer=kowitodb__pb2.GetSessionResponse.SerializeToString,
            ),
            'Stats': grpc.unary_unary_rpc_method_handler(
                    servicer.Stats,
                    request_deserializer=kowitodb__pb2.StatsRequest.FromString,
                    response_serializer=kowitodb__pb2.StatsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kowitodb.KowitoDB', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('kowitodb.KowitoDB', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class KowitoDB:
    """---- Service ----

    """

    @staticmethod
    def Insert(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kowitodb.KowitoDB/Insert',
            kowitodb__pb2.InsertRequest.SerializeToString,
            kowitodb__pb2.InsertResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BatchInsert(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kowitodb.KowitoDB/BatchInsert',
            kowitodb__pb2.BatchInsertRequest.SerializeToString,
            kowitodb__pb2.BatchInsertResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kowitodb.KowitoDB/Get',
            kowitodb__pb2.GetRequest.SerializeToString,
            kowitodb__pb2.GetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Update(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kowitodb.KowitoDB/Update',
            kowitodb__pb2.UpdateRequest.SerializeToString,
            kowitodb__pb2.UpdateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kowitodb.KowitoDB/Delete',
            kowitodb__pb2.DeleteRequest.SerializeToString,
            kowitodb__pb2.DeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kowitodb.KowitoDB/List',
            kowitodb__pb2.ListRequest.SerializeToString,
            kowitodb__pb2.ListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Search(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kowitodb.KowitoDB/Search',
            kowitodb__pb2.SearchRequest.SerializeToString,
            kowitodb__pb2.SearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Ask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kowitodb.KowitoDB/Ask',
            kowitodb__pb2.AskRequest.SerializeToString,
            kowitodb__pb2.AskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Remember(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kowitodb.KowitoDB/Remember',
            kowitodb__pb2.RememberRequest.SerializeToString,
            kowitodb__pb2.RememberResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Sql(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kowitodb.KowitoDB/Sql',
            kowitodb__pb2.SqlRequest.SerializeToString,
            kowitodb__pb2.SqlResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RecordTurn(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kowitodb.KowitoDB/RecordTurn',
            kowitodb__pb2.RecordTurnRequest.SerializeToString,
            kowitodb__pb2.RecordTurnResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kowitodb.KowitoDB/GetSession',
            kowitodb__pb2.GetSessionRequest.SerializeToString,
            kowitodb__pb2.GetSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Stats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kowitodb.KowitoDB/Stats',
            kowitodb__pb2.StatsRequest.SerializeToString,
            kowitodb__pb2.StatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
