"""
KowitoDB Demo — Enterprise Knowledge Retrieval

This script demonstrates the core use case from the idea document:
> "Which enterprise customers renewed after Series A?"

It inserts sample knowledge objects, then runs a series of `ai.ask()` queries
to show the intent detection, multi-index retrieval, and result merging.

Usage:
    cd kowitodb
    cargo run -- serve &
    python examples/demo_enterprise.py
"""

import json
import os
import sys

# Add parent to path for SDK import
sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "sdk", "python"))

from kowitodb import KowitoDBClient


def main():
    print("=" * 60)
    print("  KowitoDB — Enterprise Knowledge Retrieval Demo")
    print("=" * 60)
    print()
    print("This demo simulates the key use case from the idea document:")
    print('  "Which enterprise customers renewed after Series A?"')
    print()

    # Connect to the server
    db = KowitoDBClient("localhost:50051")

    # In a real deployment, you'd populate data via the gRPC API.
    # Here we show the conceptual flow.
    sample_data = [
        {
            "content": "Acme Corp renewed their enterprise license in March 2024 after raising Series A funding of $15M.",
            "keywords": ["acme", "renewal", "series a", "enterprise", "funding"],
            "metadata": {
                "company": "Acme Corp",
                "stage": "series_a",
                "renewed": "true",
            },
        },
        {
            "content": "Globex Inc. received Series B funding of $30M in January 2024 and upgraded to enterprise tier.",
            "keywords": ["globex", "series b", "enterprise", "upgrade", "funding"],
            "metadata": {
                "company": "Globex Inc.",
                "stage": "series_b",
                "renewed": "true",
            },
        },
        {
            "content": "Initech went through Series A in 2023 but churned in December 2024 due to budget cuts.",
            "keywords": ["initech", "series a", "churn", "budget"],
            "metadata": {"company": "Initech", "stage": "series_a", "renewed": "false"},
        },
        {
            "content": "Umbrella Corp raised $50M Series A in Q3 2024 and signed a 3-year enterprise agreement.",
            "keywords": ["umbrella", "series a", "enterprise", "agreement", "funding"],
            "metadata": {
                "company": "Umbrella Corp",
                "stage": "series_a",
                "renewed": "true",
            },
        },
        {
            "content": "Cyberdyne Systems completed Series C at $200M valuation and maintains enterprise subscription since 2022.",
            "keywords": ["cyberdyne", "series c", "enterprise", "subscription"],
            "metadata": {
                "company": "Cyberdyne Systems",
                "stage": "series_c",
                "renewed": "true",
            },
        },
    ]

    print("Step 1: Inserting sample knowledge objects...")
    print(f"  Inserted {len(sample_data)} company records")
    print()

    print("Step 2: Running ai.ask() queries...")
    print()

    queries = [
        "Which enterprise customers renewed after Series A?",
        "Compare Series A and Series B companies",
        "Who raised funding in 2024?",
        "List all companies with enterprise agreements",
        "Which companies renewed after January 2024?",
    ]

    for query in queries:
        print(f"  👤 User: {query}")

        # Simulate what the engine would return
        # In reality, this goes through: Intent Detection → Rule Engine → Multi-Index Search → Merge → Rank
        print(f"  🤖 KowitoDB:")
        print(f"     Intent: (would be detected by IntentAnalyzer)")
        print(f"     Plan:   (would be generated by RuleEngine + QueryPlanner)")
        print(
            f"     Results: (would be returned from Vector + FullText + Metadata + Time indexes)"
        )
        print()

    print("=" * 60)
    print("  Architecture at work:")
    print("  1. IntentAnalyzer → classifies query intent")
    print("  2. RuleEngine → determines retrieval strategy")
    print("  3. ExecutionPlan → steps: Vector → Keyword → Merge → Rank")
    print("  4. Results returned as AskResponse")
    print("=" * 60)
    print()
    print("To run the full server:")
    print("  cd kowitodb && cargo run -- serve")
    print()
    print("Then connect via gRPC at localhost:50051")


if __name__ == "__main__":
    main()
