/**
 * Loads the KowitoDB proto dynamically with @grpc/proto-loader and exposes a
 * typed gRPC client constructor.
 *
 * Codegen choice: we use @grpc/proto-loader's *dynamic* loading rather than a
 * static codegen step. The proto is small and stable, dynamic loading avoids a
 * heavy build toolchain (protoc/ts-proto), and we layer hand-written TypeScript
 * interfaces (see `types.ts`) on top so callers still get full type safety.
 */

import * as path from "path";
import {
  loadPackageDefinition,
  ServiceClientConstructor,
  GrpcObject,
  Client,
  ClientUnaryCall,
  Metadata,
  CallOptions,
} from "@grpc/grpc-js";
import { loadSync, Options as ProtoLoaderOptions } from "@grpc/proto-loader";

import type {
  InsertRequest,
  InsertResponse,
  BatchInsertRequest,
  BatchInsertResponse,
  ListRequest,
  ListResponse,
  GetRequest,
  GetResponse,
  UpdateRequest,
  UpdateResponse,
  DeleteRequest,
  DeleteResponse,
  SearchRequest,
  SearchResponse,
  AskRequest,
  AskResponse,
  RememberRequest,
  RememberResponse,
  SqlRequest,
  SqlResponse,
  RecordTurnRequest,
  RecordTurnResponse,
  GetSessionRequest,
  GetSessionResponse,
  StatsRequest,
  StatsResponse,
} from "./types";

/** Node-style unary RPC callback. */
export type UnaryCallback<TResponse> = (
  error: Error | null,
  response?: TResponse,
) => void;

/** Signature of a unary RPC method as generated by @grpc/grpc-js. */
type UnaryMethod<TRequest, TResponse> = {
  (
    request: TRequest,
    callback: UnaryCallback<TResponse>,
  ): ClientUnaryCall;
  (
    request: TRequest,
    metadata: Metadata,
    callback: UnaryCallback<TResponse>,
  ): ClientUnaryCall;
  (
    request: TRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: UnaryCallback<TResponse>,
  ): ClientUnaryCall;
};

/**
 * Typed view of the generated gRPC client for the `kowitodb.KowitoDB` service.
 * `proto-loader` lower-cases the first letter of each RPC method name.
 */
export interface KowitoDBGrpcClient extends Client {
  insert: UnaryMethod<InsertRequest, InsertResponse>;
  batchInsert: UnaryMethod<BatchInsertRequest, BatchInsertResponse>;
  get: UnaryMethod<GetRequest, GetResponse>;
  update: UnaryMethod<UpdateRequest, UpdateResponse>;
  delete: UnaryMethod<DeleteRequest, DeleteResponse>;
  list: UnaryMethod<ListRequest, ListResponse>;
  search: UnaryMethod<SearchRequest, SearchResponse>;
  ask: UnaryMethod<AskRequest, AskResponse>;
  remember: UnaryMethod<RememberRequest, RememberResponse>;
  sql: UnaryMethod<SqlRequest, SqlResponse>;
  recordTurn: UnaryMethod<RecordTurnRequest, RecordTurnResponse>;
  getSession: UnaryMethod<GetSessionRequest, GetSessionResponse>;
  stats: UnaryMethod<StatsRequest, StatsResponse>;
}

export interface KowitoDBGrpcClientConstructor extends ServiceClientConstructor {
  new (
    ...args: ConstructorParameters<ServiceClientConstructor>
  ): KowitoDBGrpcClient;
}

const PROTO_PATH = path.resolve(__dirname, "..", "proto", "kowitodb.proto");

const PROTO_LOADER_OPTIONS: ProtoLoaderOptions = {
  keepCase: true, // preserve snake_case field names from the proto
  longs: Number,
  enums: String,
  defaults: true,
  oneofs: true,
};

let cachedConstructor: KowitoDBGrpcClientConstructor | undefined;

/**
 * Load the proto (once, memoized) and return the typed gRPC client
 * constructor for the `kowitodb.KowitoDB` service.
 */
export function loadKowitoDBService(): KowitoDBGrpcClientConstructor {
  if (cachedConstructor) {
    return cachedConstructor;
  }

  const packageDefinition = loadSync(PROTO_PATH, PROTO_LOADER_OPTIONS);
  const proto = loadPackageDefinition(packageDefinition) as unknown as {
    kowitodb: GrpcObject & { KowitoDB: KowitoDBGrpcClientConstructor };
  };

  cachedConstructor = proto.kowitodb.KowitoDB;
  return cachedConstructor;
}
